In [6]:
import numpy as np
import pandas as pd
from IPython import display

# Defines preview options
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.3f}'.format

In [24]:
colnames=['piezo', 'amplitude'] # Change to whatever you want
test = pd.read_csv("~/Documents/hirosplacement/Data/temperature_scan/180725cooling/zeeman85+.csv", sep=";", usecols=["Piezo Voltage (V)", "Fine In 1 (V)"])

# Prints statistics of file
display.display(test.describe())
# Prints csv preview
display.display(test)

       Piezo Voltage (V)  Fine In 1 (V)
count           1018.000       1018.000
mean              96.954          2.740
std               11.527          0.129
min               77.019          2.534
25%               86.986          2.627
50%               96.958          2.699
75%              106.922          2.860
max              116.890          2.959

      Piezo Voltage (V)  Fine In 1 (V)
0                77.019          2.959
1                77.058          2.959
2                77.097          2.958
3                77.136          2.958
4                77.176          2.958
...                 ...            ...
1013            116.733          2.536
1014            116.772          2.535
1015            116.811          2.535
1016            116.850          2.534
1017            116.890          2.534

[1018 rows x 2 columns]